# Generated by Django 5.1.5 on 2025-01-29 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_fornecedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_estoque', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('categorias', models.ManyToManyField(to='produtos.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='produtos',
        ),
        migrations.RenameModel(
            old_name='fornecedores',
            new_name='Fornecedor',
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.fornecedor'),
        ),
    ]
